SiteQuestaoKafka/Models/ErrorViewModel.cs
using System;

namespace SiteQuestaoKafka.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SiteQuestaoKafka/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SiteQuestaoKafka.Models;

namespace SiteQuestaoKafka.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SiteQuestaoKafka/Controllers/VotacaoController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SiteQuestaoKafka.Kafka;

namespace SiteQuestaoKafka.Controllers
{
    public class VotacaoController : Controller
    {
        private readonly ILogger<VotacaoController> _logger;
        private readonly VotacaoProducer _producer;

        public VotacaoController(ILogger<VotacaoController> logger,
            VotacaoProducer producer)
        {
            _logger = logger;
            _producer = producer;
        }

        public async Task<IActionResult> VotoAzureDevOps()
        {
            return await ProcessarVoto("Azure DevOps");
        }

        public async Task<IActionResult> VotoGitHubActions()
        {
            return await ProcessarVoto("GitHub Actions");
        }

        public async Task<IActionResult> VotoTerraform()
        {
            return await ProcessarVoto("Terraform");
        }

        public async Task<IActionResult> VotoKubernetes()
        {
            return await ProcessarVoto("Kubernetes");
        }

        private async Task<IActionResult> ProcessarVoto(string tecnologia)
        {
            _logger.LogInformation($"Processando voto para a tecnologia: {tecnologia}");
            await _producer.Send(tecnologia);
            _logger.LogInformation($"Informações sobre o voto '{tecnologia}' enviadas para o Apache Kafka!");

            TempData["Voto"] = tecnologia;
            return RedirectToAction("Index", "Home");
        }
    }
}

SiteQuestaoKafka/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pesquisa";
}

<div class="text-center">
    <h3>Testes com Kafka</h3>
    <h5>Qual tecnologia você pretende estudar mais em breve?</h5>
    <br/>
    @Html.ActionLink("Azure DevOps", "VotoAzureDevOps", "Votacao", null, new { @class = "btn btn-primary btn-xs" })
    @Html.ActionLink("GitHub Actions", "VotoGitHubActions", "Votacao", null, new { @class = "btn btn-success btn-xs" })
    @Html.ActionLink("Terraform", "VotoTerraform", "Votacao", null, new { @class = "btn btn-info btn-xs" })
    @Html.ActionLink("Kubernetes", "VotoKubernetes", "Votacao", null, new { @class = "btn btn-danger btn-xs" })

    @if (!String.IsNullOrWhiteSpace((string)TempData["Voto"]))
    {
        <br/><br/>
        <p>Obrigado pelo seu voto: <b>@TempData["Voto"]</b></p>
    }
</div>

SiteQuestaoKafka/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SiteQuestaoKafka</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SiteQuestaoKafka</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Renato Groffe - Instância: @Environment.MachineName
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>